steps:
  githubPublishRelease:
    addClosedIssues: true
    addDeltaToLastRelease: true
    excludeLabels:
      - 'discussion'
      - 'duplicate'
      - 'invalid'
      - 'question'
      - 'wontfix'
      - 'stale'
    owner: 'JulianPSchmitt'
    repository: 'devops-cm-client'
    releaseBodyHeader: 'test'
